### ISSUE TITLE
date of the visit in the report

### ISSUE THREAD

**Issue by jmcarter17** [BenjaminRosell/elders#1]
When I add a new visit, no matter what date I choose, the date that is displayed is 0000-00-00.

**Comment by BenjaminRosell** [comment]
Correct !

This is because the date format is different in the DB, and in the datepicker plugin I am using on the extension. Should be able to fix it soon !

Thanks !!

**Comment by jmcarter17** [comment]
Allright, this is fixed, we should close this issue!
