### ISSUE TITLE
Issue in Teams if you delete a user that is assigned to a team.

### ISSUE THREAD

**Issue by jmcarter17** [BenjaminRosell/elders#6]
If you delete a user that is in a team, then the following issue happens in the home/teams page: 
ErrorException: Notice: Trying to get property of non-object in /Users/jmcarter/Sites/elders/app/storage/views/02df8f60921ed2c5a3491d6bf79b0939 line 35

Maybe, if a user gets deleted, the not assigned user should immediately take his place in the team he is in. Just like a deleted team gets replaced by team 1, a deleted user should be replaced by user 1 in his team.

**Comment by BenjaminRosell** [comment]
Done  !!

From now on, if a user is assigned to a team when deleted, the team will have the Not Assigned user assigned in his stead.
